// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWH30E2CkbGFkIKtfbU5ReeiHZ60oDigg',
    appId: '1:769828326525:web:546d1001b15a0311fe3514',
    messagingSenderId: '769828326525',
    projectId: 'chat-app-portfolio-2026',
    authDomain: 'chat-app-portfolio-2026.firebaseapp.com',
    storageBucket: 'chat-app-portfolio-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAx_gXL_iYi647XmnBnQ_RrKwD2o5J3iw',
    appId: '1:769828326525:android:77b3453fc1dd235bfe3514',
    messagingSenderId: '769828326525',
    projectId: 'chat-app-portfolio-2026',
    storageBucket: 'chat-app-portfolio-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD64EjHtW2OY4pNyzzCulB6e3fQGkfq-BE',
    appId: '1:769828326525:ios:aec9daef5f664778fe3514',
    messagingSenderId: '769828326525',
    projectId: 'chat-app-portfolio-2026',
    storageBucket: 'chat-app-portfolio-2026.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD64EjHtW2OY4pNyzzCulB6e3fQGkfq-BE',
    appId: '1:769828326525:ios:aec9daef5f664778fe3514',
    messagingSenderId: '769828326525',
    projectId: 'chat-app-portfolio-2026',
    storageBucket: 'chat-app-portfolio-2026.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWH30E2CkbGFkIKtfbU5ReeiHZ60oDigg',
    appId: '1:769828326525:web:51dff8968ddfaf00fe3514',
    messagingSenderId: '769828326525',
    projectId: 'chat-app-portfolio-2026',
    authDomain: 'chat-app-portfolio-2026.firebaseapp.com',
    storageBucket: 'chat-app-portfolio-2026.firebasestorage.app',
  );
}
